Development
carineortolani/Challenge-Frontend-Marvel pull request #1
Opened 2021-02-18 19:49 UTC by carineortolani

Desenvolvimento do desafio de Front-end em JavaScript, HTML e CSS, baseado no protótipo Marvel.

[Card Jira-LFE-138](https://liveonsolutions.atlassian.net/browse/LFE-138)

## Tipo das Modificações

Que tipo de mudança você está trazendo ao Challenge Frontend - Marvel?
_Coloque um `x` nas caixinhas que se aplicam:_

- [ ] Melhorias ou refatoração (alterações em código não-críticas);
- [ ]  Style (alterações no estilo de uma funcionalidade);
- [ ] Bugfix (mudança não-crítica que corrige um bug);
- [x] Feature (mudança não-crítica que adiciona uma funcionalidade);
- [ ] Mudança crítica (fix ou feature que pode causar problemas em funcionalidades já existentes);
- [ ] Documentações (caso seja uma documentação ou nenhuma das outras opções se aplique);

2021-02-24 18:49 UTC, hurick requested changes
@carineortolani você foi exatamente pelo caminho certo, Carine. Precisamos apenas realizar alguns ajustes para que fique o mais correto possível 😊

Parabéns pelo código, gostei bastante do que vi!

2021-02-24 18:49 UTC, hurick commented on character.html
> +<!DOCTYPE html>
@carineortolani quando eu estava na homepage, não encontrei nenhum lugar que eu pudesse clicar para ser levado para essa página.

O ideal seria que eu clicasse no herói para aí sim, entrar no detalhamento dele.

2021-02-24 18:49 UTC, hurick commented on character.html
> +      <form method="GET" action="team.html">
@carineortolani poderia me explicar melhor o porque do uso da tag `<form>` por aqui?

2021-02-24 18:49 UTC, hurick commented on character.html
> +        <button class="h__buttonYourTeam" type="submit">
@carineortolani poderia me explicar melhor o porque do uso do `type="submit"` no `<button>` por aqui?

2021-02-24 18:49 UTC, hurick commented on character.html
> +      <a class="sd__return" href="index.html">
@carineortolani assim como nas tags `<img` você adicionar o atributo `alt=" "`, em toda tag `<a>` é interessante adicionar o atributo `title=" "` por questões de acessibilidade.

2021-02-24 18:49 UTC, hurick commented on character.html
> +        <h5 class="c__subtitle"># results</h5>
@carineortolani normalmente não recomendamos a utilização de headings acima de `<h4>` por questões de SEO e encontrabilidade, visto que depois do `<h4>`, o peso deles acaba sendo próximo de um tag normal.

2021-02-24 18:49 UTC, hurick commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@carineortolani normalmente não recomendamos a utilização de headings acima de `<h4>` por questões de SEO e encontrabilidade, visto que depois do `<h4>`, o peso deles acaba sendo próximo de um tag normal.

2021-02-24 18:49 UTC, hurick commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@carineortolani normalmente não recomendamos a utilização de headings acima de `<h4>` por questões de SEO e encontrabilidade, visto que depois do `<h4>`, o peso deles acaba sendo próximo de um tag normal.

2021-02-24 18:49 UTC, hurick commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@carineortolani normalmente não recomendamos a utilização de headings acima de `<h4>` por questões de SEO e encontrabilidade, visto que depois do `<h4>`, o peso deles acaba sendo próximo de um tag normal.

2021-02-24 18:49 UTC, hurick commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@carineortolani normalmente não recomendamos a utilização de headings acima de `<h4>` por questões de SEO e encontrabilidade, visto que depois do `<h4>`, o peso deles acaba sendo próximo de um tag normal.

2021-02-24 18:49 UTC, hurick commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@carineortolani normalmente não recomendamos a utilização de headings acima de `<h4>` por questões de SEO e encontrabilidade, visto que depois do `<h4>`, o peso deles acaba sendo próximo de um tag normal.

2021-02-24 18:49 UTC, hurick commented on character.html
> +
@carineortolani essa quebra de linha não precisa existir.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +}
@carineortolani é altamente recomendado uma quebra de linha entre seletores CSS para melhor legibilidade do código, caso contrário, dá uma sensação de bagunça.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +}
@carineortolani é altamente recomendado uma quebra de linha entre seletores CSS para melhor legibilidade do código, caso contrário, dá uma sensação de bagunça.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +
@carineortolani essa quebra de linha não precisa existir.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +
@carineortolani essa quebra de linha não precisa existir.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário, você pode (e deve, para melhor legibilidade), utilizar a forma shorthand para escrever, do mesmo jeito que você deixou comentado na linha 32. Ex.:

```css
.seletor {
 font: 700 2rem/1em 'Roboto', sans-serif;
}
```

Reduzindo o código de 4 linhas para apenas 1.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +  /* (forma resumida) */
@carineortolani normalmente não deixamos que códigos comentados para que sejam enviados para o Git, justamente por não existir a necessidade.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +  /* padding: 18px 8px; */
@carineortolani normalmente não deixamos que códigos comentados para que sejam enviados para o Git, justamente por não existir a necessidade.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +
@carineortolani essa quebra de linha não precisa existir.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +
@carineortolani essa quebra de linha não precisa existir.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +  width: 24.5px;
@carineortolani normalmente não utilizamos quebras de pixel porque isso pode comprometer bastante os cálculos em telas diferentes. `.5px` em um monitor é diferente de `.5px` em uma televisão, por exemplo.

2021-02-24 18:49 UTC, hurick commented on css/modules/01-header.css
> +.header {
@carineortolani percebi que em várias seções desse arquivo, você está usando quebras de linhas entre as propriedades CSS que estão sendo alteradas.

Não sei se está seguindo algum padrão pra realizá-las ou se simplesmente aconteceram, mas se estiver seguindo um padrão, pode comentar qual é?

No caso, se for seguir algum padrão, recomendo muito o [Codeguide.co](https://codeguide.co/#css-declaration-order), onde ele mostra para que servem realmente as quebras de linhas entre essas regras e principalmente, onde realizá-las.

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +.section {
@carineortolani normalmente não utilizamos o nome de classe com o mesmo nome da tag por motivos de causar confusão.

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +.section {
@carineortolani percebi que em várias seções desse arquivo, você está usando quebras de linhas entre as propriedades CSS que estão sendo alteradas.

Não sei se está seguindo algum padrão pra realizá-las ou se simplesmente aconteceram, mas se estiver seguindo um padrão, pode comentar qual é?

No caso, se for seguir algum padrão, recomendo muito o [Codeguide.co](https://codeguide.co/#css-declaration-order), onde ele mostra para que servem realmente as quebras de linhas entre essas regras e principalmente, onde realizá-las.

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +  background-image:url(../../assets/images/backgroundmain.png);
@carineortolani aqui faltou um espaço entre a propriedade e o valor, para melhor legibilidade.

Outro ponto é que normalmente passamos o valor do método `url()` como `strings`. Ex.:

```css
.seletor {
  background-image: url('./caminho-para-a-imagem.png');
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse caso, podemos reduzir a quantidade de linhas do nosso código utilizando o formato shorthand de `font` (como já mencionado anteriormente e com exemplos).

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +  color: #ffffff;
@carineortolani aqui não está errado nada. É mais um comentário pra efeito de curiosidade mesmo.
Quando temos um hexadecimal com letras repetidas, podemos escrever ele de uma forma reduzida. Ex.:

Se temos `#ffffff` (branco), podemos escrever também `#fff`.
Se temos `#ff0000` (vermelho), podemos escrever também `#f00`.

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani por aqui também podemos utilizar o shorthand de `font` para reduzirmos linhas de código.

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +  background: #f5f5f5;
@carineortolani como aqui só estamos especificando uma regra do `background`, que no caso seria o `color`, não precisamos utilizar a versão shorthand. Podemos usar o comando direto para sermos mais objetivos na nossa comunicação. Ex.:

```css
.seletor {
  background-color: #f5f5f5;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/02-section.css
> +  background: #f43735;
@carineortolani como aqui só estamos especificando uma regra do `background`, que no caso seria o `color`, não precisamos utilizar a versão shorthand. Podemos usar o comando direto para sermos mais objetivos na nossa comunicação. Ex.:

```css
.seletor {
  background-color: #f5f5f5;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  height: 6.5625rem;
@carineortolani não está errado, mas só pra efeito de curiosidade, por convenção normalmente utilizamos no máximo 2 dígitos após a vírgula (nesse caso ponto 😂).

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário também poderia ser utilizado o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani aqui também podemos utilizar o shorhand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@carineortolani porque nesse caso você acabou optando por utilizar `filter: drop-shadow()` invés de `box-shadow` direto? 🤔

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@carineortolani porque nesse caso você acabou optando por utilizar `filter: drop-shadow()` invés de `box-shadow` direto? 🤔

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  width: 19.5px;
@carineortolani normalmente, por convenção, não utilizamos `.5px` porque, por ser uma medida fixada, `.5px` de um monitor é diferente de `.5px` de uma televisão.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani aqui também podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  padding: 0.9em 0.9em 0.6em;
@carineortolani por `em` ser uma medida proporcional, normalmente deixamos a utilização dele para fontes e altura de linhas. Para atributos como `margin` e `padding`, ainda utilizamos medidas fixas.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani aqui podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  padding: 0% 10%;
@carineortolani não está errado, mas assim como `em`, essa utilização pode ser meio perigosa e muito trabalhosa, principalmente quando estamos trabalhando com responsividade.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani por aqui também podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +.mpp__number {
@carineortolani como as regras `.mpp__number`, `.mpp__more`, `.mpp__end` e `mpp__next` possuem exatamente os mesmo atributos, você poderia reduzir código e melhor a legibilidade da seguinte forma:

```css
.mpp__number,
.mpp__more,
.mpp__end,
.mpp__next {
  text-decoration: none;
  color: #212121;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/03-main.css
> +.mpp__next{
@carineortolani aqui, como as regras de `color` e `text-decoration` já foram adicionadas acima, você só teria que deixar a regra de `margin` mesmo, que é o diferente nesse cenário.

2021-02-24 18:49 UTC, hurick commented on css/modules/04-footer.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani podemos utilizar o shorthand de `font` nessa situação.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +body {
@carineortolani temos 2 problemas por aqui.

Primeiro é a utilização da tag `<body>`. Por convenção, não devemos utilizar tags para realizar estilos específicos, por isso substituímos por classes.

E o segundo é que se `<body>` realmente precisa desse estilo, ele deveria estar no arquivo de CSS Reset junto com as outras regras base que body também possui.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani podemos utilizar o shorthand de `font` nessa situação.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  height: 7.7px;
@carineortolani aqui é o problema de usar o valor quebrado de pixel que foi citado anteriormente em outras ocasiões.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani podemos utilizar o shorthand de `font` por aqui também.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  margin-top: 98px;
@carineortolani nesse cenário, pra melhorar a legibilidade, não precisamos separar as 3 regras dessa forma, mas sim, utilizar o shorthand `margin`. Ex.:

```css
.seletor {
  margin: 98px 0 40px 30px;
}
```
Lembrando apenas que, para o valor de `margin-right`, onde você não está aplicando nada em específico, você pode utilizar tanto `0` quanto `auto`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  margin-top: 48px;
@carineortolani nesse cenário podemos utilizar o shorthand de `margin` para melhorarmos a legibilidade do nosso código. Ex.:

```css
.seletor {
  margin: 48px 35px 48px 85px;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  height: 6.5625rem;
@carineortolani utilizar esse valores de `em`, `rem` e `%` para definir a altura de um elemento é perigosíssimo, principalmente se estiver desenvolvendo algo responsivo. Pra quebrar um layout com essas definições é um tapa.

Recomendo MUITO que essa altura seja automática e que o controle de altura desse elemento seja feito baseado em seus filhos. Caso realmente precise ser uma altura fixada, sugiro trocar para medidas fixadas, como quando estamos adicionando um ícone em nosso projeto (24x24 por exemplo).

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@carineortolani poderia me explicar o porque da escolher de utilizar o `filter: drop-shadow` invés do `box-shadow` de forma direta? 🤔

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/05-character.css
> +  margin-top: 21px;
@carineortolani essa regra está se repetindo com a linha 176.
 Qual é a correta nesse cenário? 🤔

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +body {
@carineortolani temos 2 problemas por aqui.

Primeiro é a utilização da tag `<body>`. Por convenção, não devemos utilizar tags para realizar estilos específicos, por isso substituímos por classes.

E o segundo é que se `<body>` realmente precisa desse estilo, ele deveria estar no arquivo de CSS Reset junto com as outras regras base que body também possui.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário, podemos utilizar o shorthadn de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  right: 0%;
@carineortolani como `0` é um valor absoluto independente do seu tipo, você não precisa indicá-lo, podendo deixar apenas `0` nessa situação.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  height: 7.7px;
@carineortolani aqui é a questão do probleminha de utilizar pixel em valores quebrados que conversamos anteriormente.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nessa situação podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  margin-top: 98px;
@carineortolani nessa situação podemos utilizar o shorthand de `margin`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@carineortolani pode me explicar o porque da escolha de utilizar `filter: drop-shadow` e não `box-shadow` diretamente? 🤔

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  width: 19.5px;
@carineortolani aqui temos novamente o probleminha de utilizarmos valores quebrados em `px`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nessa situação podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  padding: 0.9em 0.9em 0.6em;
@carineortolani nessa situação, é o problema que conversamos anteriormente sobre as medidas proporcionais para esse atributo.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani por aqui também podemos utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  padding: 0% 10%;
@carineortolani por aqui também o probleminha de utilizarmos medidas proporcionais como conversamos anteriormente em outros arquivos.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +.mcc__img_2 {
@carineortolani nesse cenário, podemos juntar as 3 regras que possuem o mesmo atributo em apenas uma regra. Ex.:

```css
.mcc__img_2,
.mcc__img_4,
.mcc__img_3 {
  height: 169px;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  margin-top: 22px;
@carineortolani não está errado, mas nesse caso poderíamos utilizar o shorthand `margin` para melhor legibilidade. Ex.:

```css
.seletor {
  margin: 22px 0 398px;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani nesse cenário também podeoms utilizar o shorthand de `font`.

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +.mpp__number {
@carineortolani você pode reduzir a quantidade de regras que possuem atributos iguais utilizando a seguinte forma:

```css
.mpp__number,
.mpp__number,
.mpp__end,
.mpp__next {
  text-decoration: none;
  color: #212121;
}
```

2021-02-24 18:49 UTC, hurick commented on css/modules/06-team.css
> +  margin-left: 22px;
@carineortolani como as outras regras foram reduzidas acima, esse seletor vai ter apenas o atributo de `margin-left`.

2021-02-24 18:49 UTC, hurick commented on index.html
> +            <h5 class="mcc__name">Spider Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +            <h5 class="mcc__name">Iron Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +            <h5 class="mcc__name">Wolverine</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +          <h5 class="mcc__name">Spider Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +          <h5 class="mcc__name">Iron Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +            <a class="mpp__number" href="#">1</a>
@carineortolani assim como toda tag `<img>` possui um `alt=" "` para melhorar acessibilidade, as tags `<a>` também  devem receber um atributo `title=" "`.

2021-02-24 18:49 UTC, hurick commented on index.html
> +
@carineortolani não existe necessidade dessa quebra de linha 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +
@carineortolani não existe necessidade dessa quebra de linha 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +
@carineortolani não existe necessidade dessa quebra de linha 😊

2021-02-24 18:49 UTC, hurick commented on js/favorite.js
> +const heroFavorite = document.querySelectorAll('.mcc__button')
@carineortolani existe alguns pontos de refatoração por aqui, mas nada crítico.

A única coisa é que assim que possível, vamos sentar pra você me explicar linha por linha, pra entender se realmente pegou o que cada método está fazendo por aqui.

2021-02-24 18:49 UTC, hurick commented on team.html
> +          <h5 class="mcc__name">Spider Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +          <h5 class="mcc__name">Iron Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +          <h5 class="mcc__name">Captain A...</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +        <h5 class="mcc__name">Spider Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +        <h5 class="mcc__name">Iron Man</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +        <h5 class="mcc__name">Wolverine</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +        <h5 class="mcc__name">Captain A...</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +          <a class="mpp__number" href="#">1</a>
@carineortolani assim como toda tag `<img>` possui um `alt=" "` para melhorar acessibilidade, as tags `<a>` também  devem receber um atributo `title=" "`.

2021-02-24 18:49 UTC, hurick commented on index.html
> +        <form method="GET" action="team.html">
@carineortolani existe um motivo para esse `<form>` estar sendo utilizado aqui? 🤔

2021-02-24 18:49 UTC, hurick commented on team.html
> +      <form method="GET" action="team.html">
@carineortolani existe um motivo para esse `<form>` estar sendo utilizado aqui? 🤔

2021-02-24 18:49 UTC, hurick commented on team.html
> +        <button class="h__buttonYourTeam" type="submit">
@carineortolani esse botão com o atributo `type="submit`, existe algum motivo? 🤔

2021-02-24 18:49 UTC, hurick commented on index.html
> +          <button class="h__buttonYourTeam" type="submit">
@carineortolani esse botão com o atributo `type="submit`, existe algum motivo? 🤔

2021-02-24 18:49 UTC, hurick commented on index.html
> +            <h5 class="mcc__name">Captain A...</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on index.html
> +          <h5 class="mcc__name">Wolverine</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-24 18:49 UTC, hurick commented on team.html
> +          <h5 class="mcc__name">Wolverine</h5>
@carineortolani normalmente utilizamos até o `<h4>` pelo que foi comentado anteriormente em outro arquivo, sobre o caso do SEO 😊

2021-02-25 12:22 UTC, carineortolani commented on character.html
> +<!DOCTYPE html>
@hurick e seria melhor colocar quando clica no card ou no nome do herói?

2021-02-25 12:26 UTC, hurick commented on character.html
> +<!DOCTYPE html>
@carineortolani na minha visão, pensando em UX/UI, seria mais interessante colocar esse link quando você clica no card mesmo, mas tome cuidado pra não deixar isso influenciar o botão de favoritar o herói.

2021-02-25 16:58 UTC, carineortolani commented on character.html
> +      <form method="GET" action="team.html">
@hurick na verdade eu fiquei com um pouco de dúvida nessa parte... coloquei  a tag `form`, pois queria que o usuário fosse para a página do time, mas olhando agora seria melhor utilizar uma tag `a`, certo?

2021-02-25 17:44 UTC, hurick commented on character.html
> +      <form method="GET" action="team.html">
@carineortolani exatamente. `<form>` serve pra **form**ulários apenas, assim como o botão do `type="submit"` só tem um real efeito quando estiver dentro de um formulário.

2021-02-26 12:18 UTC, carineortolani commented on character.html
> +        <button class="h__buttonYourTeam" type="submit">
@hurick eu tinha entendido que todo botão tinha class e type, mas agora eu entendi que esse tipo de botão se encaixa apenas em formulários

2021-02-26 15:08 UTC, carineortolani commented on character.html
> +      <a class="sd__return" href="index.html">
@hurick certo, adicionei em todas as tags `a`

2021-02-26 16:50 UTC, carineortolani commented on character.html
> +        <h5 class="c__subtitle"># results</h5>
@hurick então eu posso voltar e usar como um `h2`?  Visto que essa parte é um dos sub-títulos da página.

2021-03-01 12:45 UTC, carineortolani commented on css/modules/01-header.css
> +  /* padding: 18px 8px; */
@hurick opa, eu tinha deixado comentado na hora que falei com os meninos, para não esquecer, por fim acabei não passando para o Notion

2021-03-01 12:50 UTC, hurick commented on character.html
> +        <button class="h__buttonYourTeam" type="submit">
@carine vamos lá.

`class` é uma variável pra cada elemento, podendo ou não existir, baseado na necessidade ou não de estilização de um elemento.

Semanticamente falando, o cada elemento `<button>` precisa sim de um atributo `type=" "`. Meu ponto apenas é que para botões genéricos, o valor dele seria um `button` invés de `submit` hehehe

2021-03-01 12:54 UTC, hurick commented on character.html
> +        <h5 class="c__subtitle"># results</h5>
@carine depende, tem que ver de acordo com o que você desenvolveu, de acordo com o padrão que você criou, podendo ser um `<h2>` ou um `<h3>`.

2021-03-01 12:54 UTC, hurick commented on css/modules/01-header.css
> +  /* padding: 18px 8px; */
@carine sem problema algum, Carine. Acontece hahahahaha

2021-03-01 13:07 UTC, carineortolani commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@hurick certo, já alterei 😊

2021-03-01 13:17 UTC, carineortolani commented on css/modules/01-header.css
> +  width: 24.5px;
@hurick ah sim, só  coloquei porque o tamanho não estava ficando igual, vou arrumar.... teria outro jeito de deixar essa medida, só que sem comprometer em outras telas?

2021-03-01 13:31 UTC, carineortolani commented on character.html
> +        <button class="h__buttonYourTeam" type="submit">
@hurick ah simm, entendi kkkkk... 

Eu fiz com `<a href=" ">` agora, mas tinha tirado o type, vou voltar adicionando ele 😊

2021-03-01 14:04 UTC, carineortolani commented on css/modules/01-header.css
> +  font-family: 'Roboto', sans-serif;
@hurick certo, eu tinha deixado da outra forma para no começo eu saber qual é qual, agora alterei para a forma shorthand.

2021-03-01 14:18 UTC, hurick commented on css/modules/01-header.css
> +  width: 24.5px;
@carineortolani como assim comprometer outras telas? Acho que não entendi muito bem a dúvida.

2021-03-01 14:20 UTC, hurick commented on character.html
> +        <button class="h__buttonYourTeam" type="submit">
@carineortolani na verdade, o certo mesmo seria usar `<a href=" ">` mesmo, Carine, visto que esse botão vai ter levar pra um novo hyperlink. O `<button type="button">` serve mais para outros tipos de ações.

2021-03-01 14:46 UTC, carineortolani commented on css/modules/01-header.css
> +.header {
@hurick acabei entendo as quebras de linha errado, vou olhar novamente Codeguide.co e arrumar essa parte da ordem e quebra de linha

2021-03-01 15:10 UTC, carineortolani commented on css/modules/02-section.css
> +.section {
@hurick ah sim, achei que como era class, não teria problema

2021-03-01 16:04 UTC, carineortolani commented on css/modules/01-header.css
> +  width: 24.5px;
@hurick sem dar muita diferença de uma tela pequena para uma maior

2021-03-02 12:20 UTC, carineortolani commented on css/modules/02-section.css
> +.section {
@hurick como disse no anterior, não tinha entendido muito bem, depois da sua explicação, ficou mais claro para mim. Estou reorganizando, também percebi que ''errei'' os nomes do class, o padrão seria `class = "algo-outra--coisa"`. 

(Porém acho melhor arrumar isso futuramente no tempo livre, para não perder muito tempo, estou sentindo que estou demorando muito no challenge 🙁)

2021-03-02 12:30 UTC, carineortolani commented on css/modules/02-section.css
> +  background: #f43735;
@hurick certo, eu não tinha visto que usei shorthand aqui. Já arrumei 😊

2021-03-02 12:41 UTC, carineortolani commented on css/modules/03-main.css
> +  height: 6.5625rem;
@hurick kkkkkkkkkkkkkkk então, o tamanho não estava ficando igual e mudar um número dava uma baita diferença, fora eu já ter convertido de pixels pra rem.... deu que acabei nesse número gigante, mas ficou bem perto do tamanho do protótipo. 

É claro que no dia a dia, não farei isso... acabei me empolgando no quesito deixar do mesmo tamanho 🤦‍♀️

2021-03-02 13:32 UTC, carineortolani commented on css/modules/03-main.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@hurick eu não sabia que os dois eram a mesma coisa, na verdade o `filter: drop-shadow()` está nas configurações de estilo do Figma, mas agora que você falou, dei uma devida atenção para ele. 

Ele não é tão compatível, quanto o `box-shadow` é com os navegadores, porém é mais indicado quando precisamos utilizar sombras em objetos muito diferentes. O que não é esse caso, já que é um circulo, sendo assim vou alterar para `box-shadow`. 😊

2021-03-02 13:36 UTC, carineortolani commented on css/modules/03-main.css
> +  width: 19.5px;
@hurick como eu deixaria essa medida, só que sem deixar fixa?

2021-03-02 14:50 UTC, carineortolani commented on css/modules/03-main.css
> +  padding: 0.9em 0.9em 0.6em;
@hurick certo, vou mudar essas para px então 😊

2021-03-02 16:03 UTC, carineortolani commented on css/modules/03-main.css
> +  padding: 0% 10%;
@hurick certo, então também vou mudar esse para px

2021-03-02 17:49 UTC, carineortolani commented on css/modules/05-character.css
> +body {
@hurick na verdade só coloquei ela, pois estava ficando com uma faixa sem cor e não entendi o que estava acontecendo, mas acredito que seja porque não coloquei estilo no main

2021-03-02 18:13 UTC, carineortolani commented on css/modules/05-character.css
> +body {
@hurick não é isso não, quando eu removo continuo com o mesmo problema 
![Captura de tela de 2021-03-02 15-11-56](https://user-images.githubusercontent.com/77004287/109694612-c57cb900-7b69-11eb-9af2-8caaed6cdfbd.png)

2021-03-02 18:31 UTC, carineortolani commented on css/modules/05-character.css
> +body {
@hurick bom, acabei colocando no reset

2021-03-02 18:49 UTC, carineortolani commented on css/modules/05-character.css
> +  margin-top: 98px;
@hurick ah sim, dessa maneira eu também economizo linhas

2021-03-02 19:09 UTC, carineortolani commented on css/modules/05-character.css
> +  height: 6.5625rem;
@hurick certo, agora entendi, já arrumei essa medida

2021-03-02 19:26 UTC, carineortolani commented on css/modules/05-character.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@hurick como comentado no anterior, eu não sabia que eles tinham basicamente a mesma função, mas agora sei que nesse caso. é melhor usar `box-shadow` 😊

2021-03-02 20:04 UTC, carineortolani commented on css/modules/05-character.css
> +  margin-top: 21px;
@hurick opa, a da linha 176, já arrumei 😊

2021-03-02 20:09 UTC, carineortolani commented on css/modules/06-team.css
> +body {
@hurick eu removi e coloquei no arquivo de CSS Reset

2021-03-03 12:11 UTC, carineortolani commented on css/modules/06-team.css
> +  right: 0%;
@hurick mas quando eu tiro o botão fica no lugar errado
![Captura de tela de 2021-03-03 09-10-33](https://user-images.githubusercontent.com/77004287/109803907-63bb5e00-7c00-11eb-8de8-77cc17a98fe2.png)

2021-03-03 12:27 UTC, hurick commented on character.html
> +            <h6 class="cn__title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pretium metus interdum dolor.</h6>
@carineortolani obrigado pela atenção nesse ponto, Carine!

2021-03-03 12:28 UTC, hurick commented on css/modules/01-header.css
> +  font-family: 'Roboto', sans-serif;
@carineortolani sem problema algum!
Obrigado pela atenção nesse ponto, Carine!

2021-03-03 12:28 UTC, hurick commented on css/modules/01-header.css
> +  width: 24.5px;
@carineortolani nesse caso você precisa trabalhar no responsivo posteriormente, não tem muito pra onde correr 😊

2021-03-03 12:29 UTC, hurick commented on css/modules/01-header.css
> +.header {
@carineortolani sem problemas, Carine!
Muito obrigado pela atenção nesse ponto!

2021-03-03 12:30 UTC, hurick commented on css/modules/02-section.css
> +.section {
@carineortolani ter problema, não tem, mas é que realmente acaba não fazendo sentido, sabe?

A nomenclatura das classes CSS é uma outra parte muito importante do código, pra poder ajudar quem está lendo e vai fazer as ediçcões.

Se eu pego esse código, eu não faço ideia de onde estou alterando. Acaba que vou ter que ir procurar no HTML todas as instâncias dessa classe.

2021-03-03 12:41 UTC, hurick commented on css/modules/02-section.css
> +.section {
@carineortolani olha, em questão de tempo, pessoalmente eu não me preocuparia muito, mas quero que faça o que mais te deixar confortável.

Sobre as classes, só pra deixar nomeado da forma correta (😂) seria `class="block-element--modifer"`. Na documentação do **BEM** você pode encontrar exemplos de como fazer essa aplicação e talvez fique mais claro de entender. Caso precise de ajuda, é só me falar.

2021-03-03 12:42 UTC, hurick commented on css/modules/02-section.css
> +  background: #f43735;
@carineortolani sem problema algum!
Obrigado pela atenção nesse ponto, Carine 😊

2021-03-03 12:43 UTC, hurick commented on css/modules/03-main.css
> +  height: 6.5625rem;
@carineortolani hahahaha não se preocupe, isso é ótimo na verdade!

A questão de ter dado esse número está correto mesmo, matematicamente falando. É mais porque em certos casos, o valor pode dar uma dízima periódica e por isso a gente acaba limitando em 2 dígitos depois da vírgula.

2021-03-03 12:45 UTC, hurick commented on css/modules/03-main.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@carineortolani Carine, PERFEITO tua resposta. É exatamente isso que vai te tornar uma desenvolvedora cada dia melhor. Exatamente isso. Fiquei super feliz.

Mas sim, os dois possuem a mesma função, por isso o questionamento, mudando apenas que o `box-shadow` é uma propriedade mais nativa que os `filter` da vida 😊

2021-03-03 12:46 UTC, hurick commented on css/modules/03-main.css
> +  width: 19.5px;
@carineortolani pra deixar a medida variável ou proporcional, você poderia usar valores proporcionais, como `%` ou `vw` por exemplo, mas dependendo da sua preocupação, é só você fazer a alteração dentro de uma media query, principalmente se for responsividade.

2021-03-03 12:47 UTC, hurick commented on css/modules/03-main.css
> +  padding: 0.9em 0.9em 0.6em;
@carineortolani boa, Carine!
Muito obrigado pela atenção nesse ponto!

2021-03-03 12:47 UTC, hurick commented on css/modules/03-main.css
> +  padding: 0% 10%;
@carineortolani boa, Carine!
Muito obrigado pela atenção nesse ponto!

2021-03-03 12:51 UTC, hurick commented on css/modules/05-character.css
> +body {
@carineortolani então, a gente só tem que dar uma analisada no que está acontecendo, mas eu posso ver depois pra você sem problema algum.

O importante desse ponto é que o seletor `body` não pode ficar espalhado por aí, visto que é uma tag que define tudo o que vai no corpo das páginas que está desenvolvendo, entendeu? A manutenibilidade disso seria muito problemática 😞

2021-03-03 12:52 UTC, hurick commented on css/modules/05-character.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@carineortolani sem problema algum, jovem!
Muito obrigado pela atenção nesse ponto.

2021-03-03 12:52 UTC, hurick commented on css/modules/05-character.css
> +  margin-top: 98px;
@carineortolani exatamente, minha querida!
Obrigado pela atenção nesse ponto!

2021-03-03 12:53 UTC, hurick commented on css/modules/05-character.css
> +  height: 6.5625rem;
@carineortolani muito obrigado pela atenção nesse ponto, querida!

2021-03-03 12:53 UTC, hurick commented on css/modules/05-character.css
> +  margin-top: 21px;
@carineortolani obrigado pela atenção nesse ponto, querida!

2021-03-03 12:53 UTC, hurick commented on css/modules/06-team.css
> +body {
@carineortolani obrigado pela atenção nesse ponto, querida!

2021-03-03 13:50 UTC, carineortolani commented on css/modules/06-team.css
> +  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
@hurick Já alterei para box-shadow 😊

2021-03-03 14:12 UTC, carineortolani commented on js/favorite.js
> +const heroFavorite = document.querySelectorAll('.mcc__button')
@hurick certo, eu imaginei que teria... quando entreguei estava procurando diminuir a quantidade de `if` 😄. 

Vamos sim, sofri bastante para fazer essa parte 😵

2021-03-03 14:25 UTC, carineortolani commented on index.html
> +        <form method="GET" action="team.html">
@hurick foi a mesma questão que expliquei nos outros arquivos, agora entendi que devo usar a tag `a`

2021-03-03 14:30 UTC, carineortolani commented on team.html
> +      <form method="GET" action="team.html">
@hurick foi a mesma questão que expliquei nos outros arquivos, agora entendi que devo usar a tag `a`

2021-03-03 14:33 UTC, carineortolani commented on team.html
> +        <button class="h__buttonYourTeam" type="submit">
@hurick foi a mesma questão do outro arquivo, agora entendi que nesse caso devo usar `type="button"`

2021-03-03 14:34 UTC, carineortolani commented on index.html
> +          <button class="h__buttonYourTeam" type="submit">
@hurick foi a mesma questão do outro arquivo, agora entendi que nesse caso devo usar `type="button"`

2021-03-03 16:52 UTC, carineortolani commented on css/modules/02-section.css
> +.section {
@hurick certo, nesse caso é a parte com fundo da imagem dos heróis, ele é igual nas três páginas, por isso deixei com esse nome... quando é assim, que nome seria melhor utilizar para deixar mais claro? 

Porque isso acontece com o cabeçalho e rodapé também.

2021-03-03 17:08 UTC, carineortolani commented on css/modules/03-main.css
> +  height: 6.5625rem;
@hurick ah simm, é nesse caso quando eu tirava, mudava o tamanho e ficava diferente kkkkkk

2021-03-03 17:11 UTC, carineortolani commented on css/modules/05-character.css
> +body {
@hurick entendi, quando eu for usar um dos seletores principais como o `body` que interfere em todas as páginas, vou me atentar e colocar no reset 😊

2021-03-04 18:57 UTC, hurick commented on css/modules/02-section.css
> +.section {
@carineortolani nesse caso, você poderia usar um classe `.featured-background`, por exemplo. `featured-bg`, algo do tipo 🤔

2021-03-04 18:59 UTC, hurick commented on js/favorite.js
> +const heroFavorite = document.querySelectorAll('.mcc__button')
@carineortolani certo, assim que finalizarmos toda a review, combinamos um dia certinho pra conversarmos sobre isso.
Valeu demais! 😊

2021-03-05 18:39 UTC, carineortolani commented on css/modules/03-main.css
> +  width: 19.5px;
@hurick certo, eu procurei mais sobre `media queries` e tentei adicionar nas minhas páginas 😊

2021-03-09 18:48 UTC, hurick commented
No arquivo `team.html`, quando eu clico no seguinte botão:

![image](https://user-images.githubusercontent.com/14249327/110521679-caec7d00-80ee-11eb-9553-51af7f3d5520.png)

Ele está voltando para a página `character.html` quando deveria voltar pra `index.html`.
Poderia fazer esse ajuste, por gentileza?

2021-03-09 18:52 UTC, hurick commented
Pensando em UX/UI, quando estou no arquivo `team.html`, não consigo voltar de forma alguma para a `index.html` que não seja o botão `Return to previous page`, o que não é o ideal.

Sugiro que o seguinte logo

![image](https://user-images.githubusercontent.com/14249327/110522038-3df5f380-80ef-11eb-9b7c-60990bc23a44.png)


seja utilizado como uma forma de link, voltando para a `index.html`, como comumente vemos em websites internet afora.

2021-03-09 18:56 UTC, hurick commented
Ainda pensando em UX/UI, sugiro os botões do projeto, como os seguintes exemplos 

![image](https://user-images.githubusercontent.com/14249327/110522288-801f3500-80ef-11eb-96f5-249b79001480.png)
![image](https://user-images.githubusercontent.com/14249327/110522544-c70d2a80-80ef-11eb-9a93-829eae52004f.png)
![image](https://user-images.githubusercontent.com/14249327/110522467-b2309700-80ef-11eb-8a8f-a46f431809e3.png)

possuam a propriedade `cursor: pointer`, para que o usuário entenda que aquele pedaço de interface possui uma ação integrada. Se não fizermos essa alteração no botão, dependendo da situação, é difícil saber quando se tem uma ação a ser executada.

2021-03-09 18:58 UTC, hurick commented
Na página `index.html`, temos o seguinte botão:

![image](https://user-images.githubusercontent.com/14249327/110522773-0c315c80-80f0-11eb-88bd-cb04a174f6e4.png)

e na página `team.html`, temos o seguinte botão:

![image](https://user-images.githubusercontent.com/14249327/110522903-33882980-80f0-11eb-8a35-7698cbf60fdf.png)

Devemos seguir o padrão feito na página `team.html`, visto que ele é o correto por questões de contraste.

2021-03-09 18:59 UTC, hurick commented
Na página `index.html`, o único personagem clicável da linha é o primeiro

![image](https://user-images.githubusercontent.com/14249327/110523098-6d593000-80f0-11eb-9288-759ab2ce50ce.png)

2021-03-09 19:00 UTC, hurick commented
Na página `team.html`, nenhum personagem é clicável para me levar ao perfil dele

![image](https://user-images.githubusercontent.com/14249327/110523210-8eba1c00-80f0-11eb-9568-342822221e2a.png)

2021-03-12 19:03 UTC, hurick approved these changes
@carineortolani PR super aprovada.

Muito massa mesmo seu trabalho, Carine! Estou muito feliz com o resultado e com a sua evolução.

Espero que seja apenas a primeira de muitas e muitas!

2021-03-18 13:14 UTC, merged